version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: trading
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: trading-system-go
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: trading
    depends_on:
      - db

volumes:
  pgdata:
